src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>School Student Date of birth</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DynamicWaysToDealWithCollections.cls
public class DynamicWaysToDealWithCollections {  
    public DynamicWaysToDealWithCollections(){
        
        List<School__c>schoolDetails=[SELECT id,Name FROM School__c];
       List<Class__c> classDetails= [SELECT id,Name FROM Class__c];
        List<Student__c> studentDetails= [SELECT id,Name,Father_Name__c,Date_of_Birth__c FROM Student__c];   
        
     Map<String,Map<String,List<Student__c>>> mapOfSchoolNameWithClassNameAndRelatedStudentsDetails = new  Map<String,Map<String,List<Student__c>>>();
        for(School__c sc:schoolDetails){
           //System.debug('School Name: ' + sc.Name);
        	for(Class__c cls:classDetails){
               //System.debug('Class name: ' + cls.Name);
                for(Student__c std:studentDetails){
               //     System.debug('Student Name: ' + std.Name);
                    Map<String, List<Student__c>> mapOfClassNameWithStudents = new Map<String, List<Student__c>>();
                    if (mapOfClassNameWithStudents.get(cls.Name) == null){
                        mapOfClassNameWithStudents.put(cls.Name, new List <Student__c> ());
                    }
                    mapOfClassNameWithStudents.get(cls.Name).add(std);
                    mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.put(sc.Name, mapOfClassNameWithStudents);    
                } 
        	}	
        }
 		system.debug(mapOfSchoolNameWithClassNameAndRelatedStudentsDetails);  
    }
}